% FIGURE12_6.M
%
% Kilian and Lutkepohl (2017), Structural VAR Analysis, Cambridge University Press.
% This file generates Figure 12.6

clear; 

% This figure loads *.mat files with the intermediate output generated by
% figureefron.m
% figurekilian.m
% figurehall.m
% figureepert.m
% figurespert.m

load efron95
subplot(3,5,1)
plot(horizon,-IRF(3,:),'r-',horizon,-CILO(3,:),'b:',horizon,-CIUP(3,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil supply shock','fontsize',13)
ylabel('Real price of oil','fontsize',14)
axis([0 h -0.075 0.075])
subplot(3,5,6)
plot(horizon,IRF(6,:),'r-',horizon,CILO(6,:),'b:',horizon,CIUP(6,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Aggregate demand shock','fontsize',13)
ylabel('Real price of oil','fontsize',14)
axis([0 h -0.05 0.1])
subplot(3,5,11)
plot(horizon,IRF(9,:),'r-',horizon,CILO(9,:),'b:',horizon,CIUP(9,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil-specific demand shock','fontsize',13)
ylabel('Real price of oil','fontsize',14)
xlabel('Months','fontsize',13)
axis([0 h 0 0.15])
clear;

load kilian95; CILO=CI1LO; CIUP=CI1UP;
subplot(3,5,2)
plot(horizon,-IRF(3,:),'r-',horizon,-CILO(3,:),'b:',horizon,-CIUP(3,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil supply shock','fontsize',13)
axis([0 h -0.075 0.075])
subplot(3,5,7)
plot(horizon,IRF(6,:),'r-',horizon,CILO(6,:),'b:',horizon,CIUP(6,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Aggregate demand shock','fontsize',13)
axis([0 h -0.05 0.1])
subplot(3,5,12)
plot(horizon,IRF(9,:),'r-',horizon,CILO(9,:),'b:',horizon,CIUP(9,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil-specific demand shock','fontsize',13)
xlabel('Months','fontsize',13)
axis([0 h 0 0.15])
clear;

load hall95
subplot(3,5,3)
plot(horizon,-IRF(3,:),'r-',horizon,-CILO(3,:),'b:',horizon,-CIUP(3,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil supply shock','fontsize',13)
axis([0 h -0.075 0.075])
subplot(3,5,8)
plot(horizon,IRF(6,:),'r-',horizon,CILO(6,:),'b:',horizon,CIUP(6,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Aggregate demand shock','fontsize',13)
axis([0 h -0.05 0.1])
subplot(3,5,13)
plot(horizon,IRF(9,:),'r-',horizon,CILO(9,:),'b:',horizon,CIUP(9,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil-specific demand shock','fontsize',13)
xlabel('Months','fontsize',13)
axis([0 h 0 0.15])
clear;

load epert95
subplot(3,5,4)
plot(horizon,-IRF(3,:),'r-',horizon,-CILO(3,:),'b:',horizon,-CIUP(3,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil supply shock','fontsize',13)
axis([0 h -0.075 0.075])
subplot(3,5,9)
plot(horizon,IRF(6,:),'r-',horizon,CILO(6,:),'b:',horizon,CIUP(6,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Aggregate demand shock','fontsize',13)
axis([0 h -0.05 0.1])
subplot(3,5,14)
plot(horizon,IRF(9,:),'r-',horizon,CILO(9,:),'b:',horizon,CIUP(9,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil-specific demand shock','fontsize',13)
xlabel('Months','fontsize',13)
axis([0 h 0 0.15])
clear;

load spert95
subplot(3,5,5)
plot(horizon,-IRF(3,:),'r-',horizon,-CILO(3,:),'b:',horizon,-CIUP(3,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil supply shock','fontsize',13)
axis([0 h -0.075 0.075])
subplot(3,5,10)
plot(horizon,IRF(6,:),'r-',horizon,CILO(6,:),'b:',horizon,CIUP(6,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Aggregate demand shock','fontsize',13)
axis([0 h -0.05 0.1])
subplot(3,5,15)
plot(horizon,IRF(9,:),'r-',horizon,CILO(9,:),'b:',horizon,CIUP(9,:),'b:',horizon,zeros(size(horizon)),'k-','linewidth',3);
title('Oil-specific demand shock','fontsize',13)
xlabel('Months','fontsize',13)
axis([0 h 0 0.15])

