function [ys_, params, info] = Bayesian_RBC_leisure_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(5)=1;
    ys_(6)=1/params(2)+params(3)-1;
    K_L=(ys_(5)*params(1)/ys_(6))^(1/(1-params(1)));
    ys_(7)=ys_(5)*(1-params(1))*K_L^params(1);
    I_L=params(3)*K_L;
    Y_L=ys_(5)*K_L^params(1);
    C_L=Y_L-I_L;
    ys_(4)=ys_(7)*params(4)/params(5)*C_L^(-1)/(1+ys_(7)*params(4)/params(5)*C_L^(-1));
    ys_(2)=C_L*ys_(4);
    ys_(8)=I_L*ys_(4);
    ys_(3)=K_L*ys_(4);
    ys_(1)=Y_L*ys_(4);
    ys_(9)=0;
    % Auxiliary equations
    check_=0;
end
