function [ys_, params, info] = BrockMirman_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(3)=1;
    ys_(2)=(ys_(3)*params(1)*params(2))^(1/(1-params(1)));
    ys_(1)=ys_(3)*ys_(2)^params(1)-ys_(2);
    % Auxiliary equations
    check_=0;
end
